# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.plugin import BasePlugin


class ImgPlugin(BasePlugin):

    def __init__(self):
        super().__init__()

    async def initialize(self) -> None:
        print("[ImgPlugin] 插件初始化开始")
        print("[ImgPlugin] 插件初始化完成")

